### PR TITLE
Add the roadmaps for beginners

### PR DESCRIPTION
**Pull request by ragu-1997**
Add some the roadmaps for beginners understanding and modify the readme file

### CODE REVIEW

**Comment by ragu-1997** [comment]
Hi team ,
Sorry for the inconvenience please remove my spam tag i can revoke my request because already i participate is done please help me

**Comment by ragu-1997** [comment]
I can edit my file please help me .i contribute so many repos it's accepted but unfortunately your case is spam

**Comment by its-red-eagle** [comment]
> I can edit my file please help me .i contribute so many repos it's accepted but unfortunately your case is spam

Show your hacktoberfest dashboard using long screenshot

**Comment by ragu-1997** [comment]
Hi vikash,

I can edit my pull request please remove my spam because I spend much more
time on it

**Comment by its-red-eagle** [comment]
Remove spam label

**Comment by ragu-1997** [comment]
Thanks

**Comment by ragu-1997** [comment]
When it's reflecting the dashboard?

**Comment by ragu-1997** [comment]
Thanks vikash am a newbie thanks for your help

**Comment by ragu-1997** [comment]
> Removed spam label
Hi team, 

Unfortunately I make some mistake you marked as a spam but now its resolved. Spam tag also removed 

my dashboard message shows like "YOU HAVE BEEN DISQUALIFIED FROM HACKTOBERFEST FOR SUBMITTING TWO OR MORE PR/MRS THAT HAVE BEEN IDENTIFIED AS SPAM.
DUE TO BEING DISQUALIFIED, YOU WILL BE INELIGIBLE TO RECIEVE ANY FURTHER REWARDS FOR YOUR PARTICIPATION IN HACKTOBERFEST." can you talk to the team . am reaching lot of time but it's not response please help me

**Pull request closed without merging**
